---
- name: nginx reload
  become: yes
  service:
    name: nginx
    state: reloaded


- name: nginx stop
  become: yes
  service:
    name: nginx
    state: stopped

- name: nginx start
  become: yes
  service:
    name: nginx
    state: started